const data = {
  products: [
    {
      name: 'air one',
      slug: 'air-small-one',
      category: 'Kits',
      image: '/images/img1.jpg',
      price: 120,
      countInstock: 10,
      rating: 4.5,
      numReviews: 10,
      desription: 'height quality air one',
    },
    {
      name: 'air two',
      slug: 'air-small-two',
      category: 'Tv',
      image: '/images/img1.jpg',
      price: 190,
      countInstock: 3,
      rating: 2,
      numReviews: 7,
      desription: 'height quality air two',
    },
    {
      name: 'air three',
      slug: 'air-small-three',
      category: 'Cams',
      image: '/images/img1.jpg',
      price: 99,
      countInstock: 20,
      rating: 3.5,
      numReviews: 5,
      desription: 'height quality air three',
    },
    {
      name: 'air four',
      slug: 'air-small-four',
      category: 'Pics',
      image: '/images/img1.jpg',
      price: 500,
      countInstock: 30,
      rating: 5,
      numReviews: 8,
      desription: 'height quality air four',
    },
  ],
};
 export default data;